### ISSUE TITLE
Operation definition in Model-First

### ISSUE THREAD

**Issue by liqian19891011** [OData/model-first#2]
After reading through the model-first.md and assumptions.md, I found a conflict of differentiating function and action.

In model-first.md
> Functions are required to specify returns; actions may do so as well.

In assumptions.md
> Operations are functions if they return something, actions otherwise

**Comment by markdstafford** [comment]
Agree that this is a bit confusing but they are not in conflict. Since functions are required to specify returns **and** since functions are idempotent, we should prefer them over actions whenever possible. So the assumption is that an operation is a function if it returns something. An operation **must** be an action if it does not return something. For actions that do return something, presumably we would have to say something like `sideeffecting: true` to clarify that it's an action, not a function. I'll open a new issue for that.
