### ISSUE TITLE
version with "1.1" will throw Simple Yaml Error

### ISSUE THREAD

**Issue by LianwMS** [OData/model-first#82]
Case 1:
Simple Yaml 
version:
    current: 1.1

Simple Yaml Error will be throw: expected type string but found type number

Case 2:
Simple Yaml
version: 3

Simple Yaml Error will be throw: expected type object but found type integer

**Comment by v-fenguo** [comment]
The Simple Yaml Error is thrown by the client browser user input error handler. So this error is for users who types in the value of the version, or the sample that contains the version value.

Luqiang Tian is the developer for this error handler and he insists that Swagger client brower requires version MUST be string.

More over, now the Error handler requires the version MUST be of this content: {current: <string value>}, however our samples are in two kinds of format (1) version: 1.0.0; (2) version: { current: 1.0.0}, and the back end logic now supports both formats and accept both number and string value.

**Comment by lqtian** [comment]
1. This field must be string. 
     1) The version can be X.X.X, etc. 
     2) If we accept numbers, something like 12e7 will also be valid, we can't restrict number format.

2. It is a YAML characteristic that string must be quoted when it likes a number, ('1', "1", '1.1', "1.1")

### Useful link
**http://symfony.com/doc/current/components/yaml/yaml_format.html**
Finally, there are other cases when **the strings must be quoted**, no matter if you're using single or double quotes:

1. When the string is true or false (otherwise, it would be treated as a boolean value);
2. When the string is null or ~ (otherwise, it would be considered as a null value);
3. **When the string looks like a number, such as integers (e.g. 2, 14, etc.), floats (e.g. 2.6, 14.9) and exponential numbers (e.g. 12e7, etc.) (otherwise, it would be treated as a numeric value);**
4. When the string looks like a date (e.g. 2014-12-31) (otherwise it would be automatically converted into a Unix timestamp).
